# Generated by Django 5.2 on 2025-04-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='health_status',
            field=models.CharField(choices=[('healthy', 'Healthy'), ('treated', 'Previously Treated'), ('never_sick', 'Never Sick')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='pond_type',
            field=models.CharField(choices=[('earthen', 'Earthen Pond'), ('concrete', 'Concrete Pond'), ('cage', 'Cage Pond'), ('tarpaulin', 'Tarpaulin Pond'), ('plastic', 'Plastic Pond')], max_length=50),
        ),
    ]
