# Generated by Django 5.1.3 on 2025-07-09 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
