# Generated by Django 5.1.3 on 2025-07-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Paystack'), ('cod', 'Cash on Delivery')], default='card', max_length=4),
        ),
    ]
